### ISSUE TITLE
API request for armies -> Not found

### ISSUE THREAD

**Issue by morteeke** [brittonhayes/aos#27]
**Describe the bug**
Hello britton, the problem I am having is that I make an API call for 'armies' and I get back the exception, "not found".
When I make a call for 'cities', I get a good response.

**To Reproduce**
1. API call "https://aos-api.com/armies"

**Expected behavior**
I expect to get a response with all armies.

**Comment by brittonhayes** [comment]
Hey @morteeke! Unfortunately this is currently expected behavior. If you check out the fixtures folder, we don't actually have any armies in the database. We do have /units and /warscrolls however.

**Comment by morteeke** [comment]
Thank you @brittonhayes for the response. I can work with units!
